name: Publish to PyPI

on:
  release:
    types: [created]  # runs when you create a GitHub Release

permissions:
  id-token: write  # Required for Trusted Publishing
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: python -m pip install --upgrade pip build twine

      - name: Build
        run: python -m build  # creates dist/*.whl and dist/*.tar.gz

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
